test_that("use", {
  lp <- rutils::validate_json_file("params/violinparams_test.json")
  validate_parameters("params/violinparams_test.json","violin_schema.json")
  expect_type(lp,"list")
  expect_warning(p <- rug_violin(lp,verbose=FALSE))
  expect_s3_class(p,"ggplot")
  print(p)
  # p <- cm_ggviolin("../../../data/iris_vio_params.json")
  # expect_s3_class(p,"ggplot")
  # lp <- list_params("params/BPermits_parameters.json","violin_schema.json")
  # # expect_type(lp,"list")
  # p <- cm_ggviolin("params/BPermits_parameters.json")
  # expect_s3_class(p,"ggplot")
})
