test_that("use", {
  # lp <- read_rugjson("params/violinparams_test.json","violin")
  lp <- read_rugjson("params/mpg_params.json","violin")
  expect_type(lp,"list")
  #expect_warning(p <- rug_violin(lp,verbose=FALSE))
  p <- rug_violin(lp,verbose=FALSE)
  expect_s3_class(p,"ggplot")
  print(p)
  # p <- cm_ggviolin("../../../data/iris_vio_params.json")
  # expect_s3_class(p,"ggplot")
  # lp <- list_params("params/BPermits_parameters.json","violin_schema.json")
  # # expect_type(lp,"list")
  # p <- cm_ggviolin("params/BPermits_parameters.json")
  # expect_s3_class(p,"ggplot")
})
